shared:
  - &prepare-director
    task: prepare-director
    file: pipelines/softlayer/tasks/prepare-director.yml
    params: &prepare-director-params
      BOSH_CLIENT:                          admin
      BOSH_CLIENT_SECRET:                   admin
      SL_USERNAME:                          {{softlayer_username}}
      SL_API_KEY:                           {{softlayer_api_key}}
      SL_DATACENTER:                        {{softlayer_datacenter}}
      SL_VLAN_PUBLIC:                       {{softlayer_vlan_public}}
      SL_VLAN_PRIVATE:                      {{softlayer_vlan_private}}
      SL_VM_NAME_PREFIX:                    {{softlayer_director_name_prefix}}
      SL_VM_DOMAIN:                         {{softlayer_director_host_domain}}

  - &deploy-director
    task: deploy-director
    file: pipelines/shared/tasks/deploy-director.yml
    params: *prepare-director-params

  - &prepare-bats
    task: prepare-bats
    file: pipelines/softlayer/tasks/prepare-bats.yml
    params: &prepare-bats-params
      BOSH_CLIENT:                          admin
      BOSH_CLIENT_SECRET:                   admin
      BAT_VCAP_PASSWORD:      {{bat-vcap-password}}
      BAT_SECOND_STATIC_IP:       {{bat_second_static_ip}}
      SL_DATACENTER:              {{softlayer_datacenter}}
      SL_VLAN_PUBLIC:             {{softlayer_vlan_public}}
      SL_VLAN_PRIVATE:            {{softlayer_vlan_private}}
      SL_VM_NAME_PREFIX:          {{softlayer_bats_name_prefix}}
      SL_VM_DOMAIN: {{softlayer_director_host_domain}}

  - &run-bats
    task: run-bats
    file: pipelines/shared/tasks/run-bats.yml

  - &teardown
    task: teardown
    file: pipelines/shared/tasks/teardown.yml
    params:
      DEPLOYMENT_NAME: certification

jobs:
  - name: build-candidate
    serial: true
    plan:
    - aggregate:
      - {trigger: false, get: bosh-cpi-release, resource: bosh-cpi-release-in}
      - {trigger: false, get: version-semver, params: {bump: major}}
      - {trigger: false, get: bosh-cli, resource: bosh-cli}

    - task: build
      file: bosh-cpi-release/ci/tasks/build-candidate.yml

    - put: version-semver
      params: {file: version-semver/number}

    - put: bosh-cpi-dev-artifacts
      params: {file: candidate/*.tgz}

  - name: bats-ubuntu
    serial: false
    plan:
    - do:
      - aggregate:
        - get: bosh-release
        - get: cpi-release
          resource: bosh-cpi-dev-artifacts
          passed:
            - build-candidate
        - get: stemcell
          trigger: true
          resource: light-stemcell
        - get: pipelines
        - get: bosh-cli
        - get: bats

      - <<: *prepare-director

      - do:
        - <<: *deploy-director

        - <<: *prepare-bats
          params:
            <<: *prepare-bats-params
            STEMCELL_NAME: bosh-softlayer-xen-ubuntu-trusty-go_agent

        - <<: *run-bats
        ensure:
          do:
          - <<: *teardown

  - name: promote-candidate
    plan:
    - aggregate:
      - {trigger: true,  get: bosh-cpi-dev-artifacts, passed: [bats-ubuntu]}
      - {trigger: false, get: bosh-cpi-release, resource: bosh-cpi-release-out}
      - {trigger: false, get: version-semver,  resource: version-semver}

    - task: promote
      file: bosh-cpi-release/ci/tasks/promote-candidate.yml
      params:
        S3_ACCESS_KEY_ID:     {{s3_access_key__primary}}
        S3_SECRET_ACCESS_KEY: {{s3_secret_key__primary}}

    - put: bosh-cpi-release-out
      params: {repository: promoted/repo, rebase: true, tag_prefix: "v", tag: promoted/integer_version}

    - put: bosh-cpi-final-artifacts
      params: {file: promoted/repo/releases/bosh-softlayer-cpi/*.tgz}

resources:
  - name: bosh-release
    type: s3
    source:
      regexp: bosh-([0-9]+)\.tgz
      bucket: {{s3_pipeline_bucket}}
      access_key_id: {{s3_access_key_id}}
      secret_access_key: {{s3_secret_access_key}}

  - name: light-stemcell
    type: s3
    source:
      regexp: light-bosh-stemcell-(\d+\.\d+)-softlayer-xen-ubuntu-trusty-go_agent\.tgz
      bucket: bosh-softlayer-stemcells-bluemix
      access_key_id: {{s3_access_key_id}}
      secret_access_key: {{s3_secret_access_key}}

  - name: bosh-cli
    type: s3
    source:
      regexp: bosh-cli-([0-9.]+)-linux-amd64
      bucket: bosh-cli-artifacts
      region_name: us-east-1

  - name: pipelines
    type: git
    source:
      uri: https://github.com/zhanggbj/bosh-cpi-certification
      branch: master

  - name: bats
    type: git
    source:
      uri: https://github.com/mattcui/bosh-acceptance-tests
      branch: master

  - name: bosh-cpi-release-in
    type: git
    source:
      uri: git@github.com:zhanggbj/bosh-softlayer-cpi-release.git
      branch: master
      private_key: {{github_private_key_zhanggbj}}
      ignore_paths:
          - .final_builds/**/*.yml
          - releases/**/*.yml

  - name: version-semver
    type: semver
    source:
      key:               current-version
      bucket:            {{s3_pipeline_bucket}}
      access_key_id:     {{s3_access_key_id}}
      secret_access_key: {{s3_secret_access_key}}

  - name: bosh-cpi-dev-artifacts
    type: s3
    source:
      regexp: bosh-softlayer-cpi-(\d+\.\d+\.\d+)\.tgz
      bucket: {{s3_pipeline_bucket}}
      access_key_id: {{s3_access_key_id}}
      secret_access_key: {{s3_secret_access_key}}

  - name: bosh-cpi-release-out
    type: git
    source:
      uri: git@github.com:zhanggbj/bosh-softlayer-cpi-release.git
      branch: master
      private_key: {{github_private_key_zhanggbj}}

  - name: bosh-cpi-final-artifacts
    type: s3
    source:
      regexp: bosh-softlayer-cpi-([0-9.]+)\.tgz
      bucket: {{s3_pipeline_bucket}}
      access_key_id: {{s3_access_key_id}}
      secret_access_key: {{s3_secret_access_key}}